RGBLIGHT_ENABLE = yes

OLED_ENABLE = yes

VIA_ENABLE = yes

EXTRAKEY_ENABLE = yes

# DEFERRED_EXEC_ENABLE = yes

# MOUSEKEY_ENABLE = no
# NKRO_ENABLE = no
# CONSOLE_ENABLE = no
# UNICODE_ENABLE = no
# BLUETOOTH_ENABLE = no
# AUDIO_ENABLE = no
# COMBO_ENABLE = no
# ENCODER_ENABLE = no
# LEADER_ENABLE = no
# MIDI_ENABLE = no
# TAP_DANCE_ENABLE = no
# TERMINAL_ENABLE = no
# STENO_ENABLE = no

# SPACE_CADET_ENABLE = no
# GRAVE_ESC_ENABLE = yes
# MAGIC_ENABLE = no

# AVR_USE_MINIMAL_PRINTF = yes
